version: "3"

services:
  mongo:
    container_name: trades-mongo
    image: mongo:3.4
    hostname: mongo
    ports:
      - 27017:27017
  #    volumes:
  #      - mongodata:/data/db
  rabbitmq:
    image: heidiks/rabbitmq-delayed-message-exchange:latest
    container_name: trades-rabbit
    ports:
      - 5672:5672
      - 15672:15672